In [2]:
import numpy as np
import pandas as pd

In [3]:
#Loading the file into a pandas dataframe using separator as None and engine as python to avoid any parsing errors
df = pd.read_csv("mymoviedb.csv", sep=None, engine="python")
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

In [4]:
#Finding the data types of each columns
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9837 entries, 0 to 9836
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9837 non-null   str
 1   Title              9828 non-null   str
 2   Overview           9828 non-null   str
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9827 non-null   str
 5   Vote_Average       9827 non-null   str
 6   Original_Language  9827 non-null   str
 7   Genre              9826 non-null   str
 8   Poster_Url         9826 non-null   str
dtypes: float64(1), str(8)
memory usage: 691.8 KB

In [5]:
#Finding the number of duplicate rows in the dataset
df.duplicated().sum()

np.int64(0)

In [6]:
#Describing the dataset to get a statistical summary of the numerical columns
df.describe()

        Popularity
count  9827.000000
mean     40.320570
std     108.874308
min       7.100000
25%      16.127500
50%      21.191000
75%      35.174500
max    5083.954000

In [7]:
#Converting the Vote_Count and Vote_Average columns to numeric data types, coercing errors to NaN
df["Vote_Count"] = pd.to_numeric(df["Vote_Count"], errors="coerce")
df["Vote_Average"] = pd.to_numeric(df["Vote_Average"], errors="coerce")

df.describe()

        Popularity    Vote_Count  Vote_Average
count  9827.000000   9826.000000   9826.000000
mean     40.320570   1392.943721      6.439467
std     108.874308   2611.303856      1.129797
min       7.100000      0.000000      0.000000
25%      16.127500    146.000000      5.900000
50%      21.191000    444.000000      6.500000
75%      35.174500   1376.000000      7.100000
max    5083.954000  31077.000000     10.000000

In [8]:
#vote_count and vote_average columns are converted and confirmed the changes
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9837 entries, 0 to 9836
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9837 non-null   str
 1   Title              9828 non-null   str
 2   Overview           9828 non-null   str
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9826 non-null   float64
 5   Vote_Average       9826 non-null   float64
 6   Original_Language  9827 non-null   str
 7   Genre              9826 non-null   str
 8   Poster_Url         9826 non-null   str
dtypes: float64(3), str(6)
memory usage: 691.8 KB

In [9]:
#converting the Release_Date column to datetime format, coercing errors=lets the conversion continue, but turns invalid date values into NaT
df["Release_Date"] = pd.to_datetime(df["Release_Date"], errors="coerce")
print(df["Release_Date"].dtypes)

datetime64[us]

In [10]:
# check which rows couldn’t be converted:
df.loc[df["Release_Date"].isna(), ["Title", "Release_Date"]].head()

     Title Release_Date
1106   NaN          NaT
1107   NaN          NaT
1108   NaN          NaT
1109   NaN          NaT
1110   NaN          NaT

In [11]:
# converting the date into int and checking its types and keeping only released year in the Release_Date column
df["Release_Date"] = df["Release_Date"].dt.year
df["Release_Date"].dtypes

dtype('float64')

In [12]:
# converting the Release_Date column to Int64 data type to handle missing values
df["Release_Date"] = df["Release_Date"].astype("Int64")

# checking the result from int conversion
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940.0,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151.0,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122.0,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076.0,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793.0,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

In [13]:
# Dropping the columns that are not needed for analysis
cols = ["Overview", "Original_Language", "Poster_Url"]
df.drop(columns=cols, inplace=True, errors="ignore")

df.head()

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940.0,8.3,"Action, Adventure, Science Fiction"
1,2022,The Batman,3827.658,1151.0,8.1,"Crime, Mystery, Thriller"
2,2022,No Exit,2618.087,122.0,6.3,Thriller
3,2021,Encanto,2402.201,5076.0,7.7,"Animation, Comedy, Family, Fantasy"
4,2021,The King's Man,1895.511,1793.0,7.0,"Action, Adventure, Thriller, War"

In [14]:
# Creating the user defined function to labels the vote_average column into 5 categories based on the given conditions
# It is aa user defined function.
def categorize_col(df, col, labels):
    edges = [df[col].describe()["min"],
             df[col].describe()["25%"],
             df[col].describe()["50%"],
             df[col].describe()["75%"],
             df[col].describe()["max"]]

    df[col] = pd.cut(df[col], edges, labels=labels, duplicates="drop")

    return df

In [15]:
#Categorizing Vote Column into 4 categories based on the given conditions and storing the labels in a list
labels = ["not_popular", "below_avg", "average", "popular"]

categorize_col(df, "Vote_Average", labels)

df["Vote_Average"].unique()

['popular', 'below_avg', 'average', 'not_popular', NaN]
Categories (4, str): ['not_popular' < 'below_avg' < 'average' < 'popular']

In [16]:
df.head()

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940.0,popular,"Action, Adventure, Science Fiction"
1,2022,The Batman,3827.658,1151.0,popular,"Crime, Mystery, Thriller"
2,2022,No Exit,2618.087,122.0,below_avg,Thriller
3,2021,Encanto,2402.201,5076.0,popular,"Animation, Comedy, Family, Fantasy"
4,2021,The King's Man,1895.511,1793.0,average,"Action, Adventure, Thriller, War"

In [17]:
#Finding the value counts of the Vote_Average column to see how many movies fall into each category
df['Vote_Average'].value_counts()

Vote_Average
not_popular    2467
popular        2450
average        2411
below_avg      2398
Name: count, dtype: int64

In [18]:
#Dropping the duplicate  and nan values
df.dropna(inplace=True)
df.isna().sum()

Release_Date    0
Title           0
Popularity      0
Vote_Count      0
Vote_Average    0
Genre           0
dtype: int64

In [19]:
#Splitting our genre to explode our dataframe more to see how many fall in each genre.
df['Genre'] = df['Genre'].str.split(', ')

df = df.explode('Genre').reset_index(drop=True)

df.head()

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940.0,popular,Action
1,2021,Spider-Man: No Way Home,5083.954,8940.0,popular,Adventure
2,2021,Spider-Man: No Way Home,5083.954,8940.0,popular,Science Fiction
3,2022,The Batman,3827.658,1151.0,popular,Crime
4,2022,The Batman,3827.658,1151.0,popular,Mystery

In [20]:
#Casting coloumn into Category
df["Genre"] = df["Genre"].astype("category")
df["Genre"].dtypes

CategoricalDtype(categories=['Action', 'Adventure', 'Animation', 'Comedy', 'Crime',
                  'Documentary', 'Drama', 'Family', 'Fantasy', 'History',
                  'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction',
                  'TV Movie', 'Thriller', 'War', 'Western'],
, ordered=False, categories_dtype=str)

In [21]:
#getting current info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25551 entries, 0 to 25550
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Release_Date  25551 non-null  Int64
 1   Title         25551 non-null  str
 2   Popularity    25551 non-null  float64
 3   Vote_Count    25551 non-null  float64
 4   Vote_Average  25551 non-null  category
 5   Genre         25551 non-null  category
dtypes: Int64(1), category(2), float64(2), str(1)
memory usage: 873.8 KB

In [22]:
#Getting unique data
df.nunique()

Release_Date     100
Title           9414
Popularity      8087
Vote_Count      3265
Vote_Average       4
Genre             19
dtype: int64

In [23]:
# All the  Data is pre processed now and ready to visualized
df.head()

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940.0,popular,Action
1,2021,Spider-Man: No Way Home,5083.954,8940.0,popular,Adventure
2,2021,Spider-Man: No Way Home,5083.954,8940.0,popular,Science Fiction
3,2022,The Batman,3827.658,1151.0,popular,Crime
4,2022,The Batman,3827.658,1151.0,popular,Mystery

In [24]:
#Checking the directory
import os
os.getcwd()

'/Users/a91843/Desktop/Major Project'

In [25]:
#Saveing it in a format to preserve.
df.to_pickle("movies_preprocessed.pkl")

In [26]:
df.to_csv("movies_cleaned.csv", index=False)