In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame([1, 2, 3, 4, 5])
print(df)

   0
0  1
1  2
2  3
3  4
4  5

In [4]:
print(type(df))

<class 'pandas.DataFrame'>

In [5]:
df.head()

   0
0  1
1  2
2  3
3  4
4  5

In [7]:
df.tail(2)

   0
3  4
4  5

In [8]:
df.shape

(5, 1)

In [9]:
df.columns

RangeIndex(start=0, stop=1, step=1)

In [11]:
df.rename(columns = {'Salary':'Pay'},inplace = True)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [13]:
df.describe()

              0
count  5.000000
mean   3.000000
std    1.581139
min    1.000000
25%    2.000000
50%    3.000000
75%    4.000000
max    5.000000

In [14]:
df.to_csv('practice.csv')

In [16]:
pd.read_csv('practice.csv')

   Unnamed: 0  0
0           0  1
1           1  2
2           2  3
3           3  4
4           4  5

In [20]:
load = pd.read_csv('practice.csv')

In [23]:


data = {
    'Name': ['ravi', 'Bitu', 'kavi', 'riya'],
    'Age': [21, 22, 23, 24],
    'Salary': [9000, 24000, 20000, 50000]
}

df = pd.DataFrame(data)

print(df)

   Name  Age  Salary
0  ravi   21    9000
1  Bitu   22   24000
2  kavi   23   20000
3  riya   24   50000

In [24]:
df.rename(columns = {'Salary':'Pay'},inplace = True)

In [25]:
df['Name']

0    ravi
1    Bitu
2    kavi
3    riya
Name: Name, dtype: str

In [26]:
df[['Name', 'Pay']]

   Name    Pay
0  ravi   9000
1  Bitu  24000
2  kavi  20000
3  riya  50000

In [27]:
df.loc[df.Name == 'ravi']

   Name  Age   Pay
0  ravi   21  9000

In [28]:
df.loc[(df.Name == 'ravi') & (df.Age == 21)]

   Name  Age   Pay
0  ravi   21  9000

In [29]:
df.iloc[2]

Name     kavi
Age        23
Pay     20000
Name: 2, dtype: object

In [30]:
df.iloc[0 : 3]

   Name  Age    Pay
0  ravi   21   9000
1  Bitu   22  24000
2  kavi   23  20000

In [33]:
df[df['Age'] < 22]

   Name  Age   Pay
0  ravi   21  9000

In [35]:
df[df['Age'] > 21]

   Name  Age    Pay
1  Bitu   22  24000
2  kavi   23  20000
3  riya   24  50000