In [5]:
import pandas as pd

In [6]:
df = pd.DataFrame([1, 2, 3, 4, 5])
print(df)

   0
0  1
1  2
2  3
3  4
4  5

In [7]:
print(type(df))

<class 'pandas.DataFrame'>

In [8]:
df.head()

   0
0  1
1  2
2  3
3  4
4  5

In [9]:
df.tail(2)

   0
3  4
4  5

In [10]:
df.shape

(5, 1)

In [11]:
df.columns

RangeIndex(start=0, stop=1, step=1)

In [12]:
df.rename(columns = {'Salary':'Pay'},inplace = True)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [14]:
df.describe()

              0
count  5.000000
mean   3.000000
std    1.581139
min    1.000000
25%    2.000000
50%    3.000000
75%    4.000000
max    5.000000

In [15]:
df.to_csv('practice.csv')

In [16]:
pd.read_csv('practice.csv')

   Unnamed: 0  0
0           0  1
1           1  2
2           2  3
3           3  4
4           4  5

In [17]:
load = pd.read_csv('practice.csv')

In [18]:


data = {
    'Name': ['ravi', 'Bitu', 'kavi', 'riya'],
    'Age': [21, 22, 23, 24],
    'Salary': [9000, 24000, 20000, 50000]
}

df = pd.DataFrame(data)

print(df)

   Name  Age  Salary
0  ravi   21    9000
1  Bitu   22   24000
2  kavi   23   20000
3  riya   24   50000

In [19]:
df.rename(columns = {'Salary':'Pay'},inplace = True)

In [20]:
df['Name']

0    ravi
1    Bitu
2    kavi
3    riya
Name: Name, dtype: str

In [21]:
df[['Name', 'Pay']]

   Name    Pay
0  ravi   9000
1  Bitu  24000
2  kavi  20000
3  riya  50000

In [22]:
df.loc[df.Name == 'ravi']

   Name  Age   Pay
0  ravi   21  9000

In [23]:
df.loc[(df.Name == 'ravi') & (df.Age == 21)]

   Name  Age   Pay
0  ravi   21  9000

In [24]:
df.iloc[2]

Name     kavi
Age        23
Pay     20000
Name: 2, dtype: object

In [25]:
df.iloc[0 : 3]

   Name  Age    Pay
0  ravi   21   9000
1  Bitu   22  24000
2  kavi   23  20000

In [26]:
df[df['Age'] < 22]

   Name  Age   Pay
0  ravi   21  9000

In [27]:
df[df['Age'] > 21]

   Name  Age    Pay
1  Bitu   22  24000
2  kavi   23  20000
3  riya   24  50000

In [28]:
df[(df['Age'] > 21) & (df['Pay'] > 20000)]

   Name  Age    Pay
1  Bitu   22  24000
3  riya   24  50000

In [29]:
df.where(df['Age'] >= 22)

   Name   Age      Pay
0   NaN   NaN      NaN
1  Bitu  22.0  24000.0
2  kavi  23.0  20000.0
3  riya  24.0  50000.0

In [30]:
df['Team'] = ['CEO', 'Manager', 'Developer', 'Designer']
df

   Name  Age    Pay       Team
0  ravi   21   9000        CEO
1  Bitu   22  24000    Manager
2  kavi   23  20000  Developer
3  riya   24  50000   Designer

In [31]:
df['Bonus'] = df['Pay'] * 0.2
df

   Name  Age    Pay       Team    Bonus
0  ravi   21   9000        CEO   1800.0
1  Bitu   22  24000    Manager   4800.0
2  kavi   23  20000  Developer   4000.0
3  riya   24  50000   Designer  10000.0

In [32]:
df.loc[len(df)] = ['tina',25,75000,'IT',2000]
len(df)

5

In [33]:
df

   Name  Age    Pay       Team    Bonus
0  ravi   21   9000        CEO   1800.0
1  Bitu   22  24000    Manager   4800.0
2  kavi   23  20000  Developer   4000.0
3  riya   24  50000   Designer  10000.0
4  tina   25  75000         IT   2000.0

In [34]:
df.loc[0,'Pay'] = 10000
df

   Name  Age    Pay       Team    Bonus
0  ravi   21  10000        CEO   1800.0
1  Bitu   22  24000    Manager   4800.0
2  kavi   23  20000  Developer   4000.0
3  riya   24  50000   Designer  10000.0
4  tina   25  75000         IT   2000.0

In [35]:
df.loc[df.Name == 'riya', 'Pay'] = 60000
df

   Name  Age    Pay       Team    Bonus
0  ravi   21  10000        CEO   1800.0
1  Bitu   22  24000    Manager   4800.0
2  kavi   23  20000  Developer   4000.0
3  riya   24  60000   Designer  10000.0
4  tina   25  75000         IT   2000.0

In [36]:
df.drop(df[df.Name == 'tina'].index)

   Name  Age    Pay       Team    Bonus
0  ravi   21  10000        CEO   1800.0
1  Bitu   22  24000    Manager   4800.0
2  kavi   23  20000  Developer   4000.0
3  riya   24  60000   Designer  10000.0

In [37]:
df.drop('Bonus',axis = 1,inplace = True)

In [38]:
df.sort_values('Pay')

   Name  Age    Pay       Team
0  ravi   21  10000        CEO
2  kavi   23  20000  Developer
1  Bitu   22  24000    Manager
3  riya   24  60000   Designer
4  tina   25  75000         IT

In [39]:
df.sort_values(by='Pay', ascending=False)

   Name  Age    Pay       Team
4  tina   25  75000         IT
3  riya   24  60000   Designer
1  Bitu   22  24000    Manager
2  kavi   23  20000  Developer
0  ravi   21  10000        CEO

In [40]:
df

   Name  Age    Pay       Team
0  ravi   21  10000        CEO
1  Bitu   22  24000    Manager
2  kavi   23  20000  Developer
3  riya   24  60000   Designer
4  tina   25  75000         IT

In [41]:
df['DOJ'] = ['2020-01-01', '2019-05-15', '2021-07-20', '2018-11-30', '2022-03-10']
df

   Name  Age    Pay       Team         DOJ
0  ravi   21  10000        CEO  2020-01-01
1  Bitu   22  24000    Manager  2019-05-15
2  kavi   23  20000  Developer  2021-07-20
3  riya   24  60000   Designer  2018-11-30
4  tina   25  75000         IT  2022-03-10

In [42]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [44]:
df['DOJ'].dt.year

0    2020
1    2019
2    2021
3    2018
4    2022
Name: DOJ, dtype: int32

In [45]:
df['DOJ'].dt.month

0     1
1     5
2     7
3    11
4     3
Name: DOJ, dtype: int32

In [46]:
df['DOJ'].dt.day

0     1
1    15
2    20
3    30
4    10
Name: DOJ, dtype: int32

In [47]:
df['DOJ'].dt.day_name

In [48]:
df['Month'] = df['DOJ'].dt.month

In [49]:
df['DOJ'] + pd.Timedelta(days=90)

0   2020-03-31
1   2019-08-13
2   2021-10-18
3   2019-02-28
4   2022-06-08
Name: DOJ, dtype: datetime64[us]

In [50]:
df.isnull
df

   Name  Age    Pay       Team        DOJ  Month
0  ravi   21  10000        CEO 2020-01-01      1
1  Bitu   22  24000    Manager 2019-05-15      5
2  kavi   23  20000  Developer 2021-07-20      7
3  riya   24  60000   Designer 2018-11-30     11
4  tina   25  75000         IT 2022-03-10      3